# Generated by Django 4.2.11 on 2024-03-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_id_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
