# Generated by Django 4.2.11 on 2024-04-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20230328_1430'),
        ('users', '0012_alter_company_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInvitation',
            fields=[
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invitations.invitation')),
                ('custom_message', models.TextField()),
                ('expiration_time', models.DateTimeField()),
                ('uses_remaining', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
