# Generated by Django 4.2.11 on 2024-04-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_custominvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomInvitation',
        ),
    ]
