# Generated by Django 4.2.11 on 2024-04-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_custominvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('REGULAR USER', 'REGULAR USER')], max_length=20),
        ),
    ]
