# Generated by Django 4.2.11 on 2024-04-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('REGULAR USER', 'REGULAR USER')], default='ADMIN', max_length=20),
        ),
    ]
