# Generated by Django 4.2.11 on 2025-04-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_customuser_role_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='company_id',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
