# Generated by Django 4.2.11 on 2025-10-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
