# Generated by Django 4.2.11 on 2025-10-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_supplier_supplier_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_measurement', models.CharField(max_length=200)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'quantities',
                'unique_together': {('company_id', 'type_of_measurement')},
            },
        ),
    ]
