# Generated by Django 4.2.11 on 2025-10-30 20:05

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='quantity',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='quantity',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('type_of_measurement'), models.F('company_id'), name='uniq_company_measurement_ci'),
        ),
    ]
