# Generated by Django 4.2.11 on 2025-11-01 14:43

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_quantity_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quantity',
            name='uniq_company_measurement_ci',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='quantity',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('type_of_measurement'), models.F('company_id'), name='uniq_company_measurement_ci', violation_error_message='Measurement already registered!'),
        ),
    ]
