# Generated by Django 4.2.11 on 2025-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_quantity_uniq_company_measurement_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company_id', 'name'), name='uniq_company_supplier_name', violation_error_message='Supplier with this name already exists in this company!'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company_id', 'email'), name='uniq_company_supplier_email', violation_error_message='Supplier with this email already exists in this company!'),
        ),
    ]
