# Generated by Django 4.2.11 on 2025-11-15 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_supplier_email_alter_supplier_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productCategory', to='company.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('category'), models.F('company'), name='uniq_company_product_category_ci', violation_error_message='Product category with this name already exists in this company!'),
        ),
    ]
