# Generated by Django 4.2.11 on 2025-11-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_productcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.DecimalField(decimal_places=2, help_text='Enter VAT rate as a percentage (e.g., 9.00 for 9%, 23.00 for 23%)', max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vatRates', to='company.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vatrate',
            constraint=models.UniqueConstraint(models.F('vat_rate'), models.F('company'), name='uniq_company_vat_rate', violation_error_message='Vat rate already registered!'),
        ),
    ]
