# Generated by Django 4.2.11 on 2025-11-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_vatrate_vatrate_uniq_company_vat_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantity',
            new_name='ProductMeasurement',
        ),
        migrations.RemoveConstraint(
            model_name='vatrate',
            name='uniq_company_vat_rate',
        ),
        migrations.AddConstraint(
            model_name='vatrate',
            constraint=models.UniqueConstraint(fields=('vat_rate', 'company'), name='uniq_company_vat_rate', violation_error_message='Vat rate already registered!'),
        ),
    ]
