# Generated by Django 4.2.11 on 2025-11-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_quantity_productmeasurement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.PositiveIntegerField(editable=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_total_price_without_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_total_price_with_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_total_vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_created_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.company')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.productcategory')),
                ('product_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.productmeasurement')),
                ('product_vat_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.vatrate')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.supplier')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'product_code'), name='uniq_company_product_code', violation_error_message='Product code already exists in this company!'),
        ),
    ]
