# Generated by Django 4.2.11 on 2025-11-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_product_product_uniq_company_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_total_price_with_vat',
            new_name='product_price_with_vat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_total_price_without_vat',
            new_name='product_price_without_vat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_total_vat_amount',
            new_name='product_vat_amount',
        ),
    ]
