# Generated by Django 4.2.11 on 2025-12-10 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0011_rename_product_total_price_with_vat_product_product_price_with_vat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('order_created_date', models.DateField(auto_now_add=True)),
                ('order_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='company.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.product')),
                ('product_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='company.productmeasurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
