# Generated by Django 4.2.11 on 2025-12-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_measurement',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item_created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='company.supplier'),
        ),
    ]
