# Generated by Django 4.2.11 on 2025-12-10 16:46

from django.db import migrations, models
import django.db.models.deletion


def set_default_product_measurement(apps, schema_editor):
    """Set default product_measurement_id from product's measurement"""
    OrderItem = apps.get_model('company', 'OrderItem')
    ProductMeasurement = apps.get_model('company', 'ProductMeasurement')
    Product = apps.get_model('company', 'Product')
    
    # Get the first ProductMeasurement as a fallback
    first_measurement = ProductMeasurement.objects.first()
    
    if not first_measurement:
        # If no ProductMeasurement exists, we can't proceed
        return
    
    # For existing OrderItems, set measurement from their product
    for order_item in OrderItem.objects.filter(product_measurement_id__isnull=True):
        try:
            # Access the product through the foreign key
            product = order_item.product_id
            if product and product.product_measurement:
                order_item.product_measurement_id = product.product_measurement
            else:
                order_item.product_measurement_id = first_measurement
            order_item.save()
        except Exception:
            # If anything fails, use the first measurement as fallback
            order_item.product_measurement_id = first_measurement
            order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_remove_orderitem_product_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_measurement_id',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_order_items', to='company.productmeasurement'),
        ),
        migrations.RunPython(set_default_product_measurement),
        migrations.AlterField(
            model_name='orderitem',
            name='product_measurement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_order_items', to='company.productmeasurement'),
        ),
    ]
