# Generated by Django 4.2.11 on 2025-12-10 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0014_orderitem_product_measurement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order_items', to='company.supplier'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_order_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
